# Generated by Django 2.0 on 2018-05-14 15:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40, verbose_name='用户名')),
                ('contract', models.CharField(max_length=100, verbose_name='合同名')),
                ('sale', models.CharField(max_length=100, verbose_name='客户经理')),
                ('email', models.EmailField(max_length=254, verbose_name='客户经理邮箱')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建日期')),
                ('mod_date', models.DateTimeField(auto_now=True, verbose_name='最后修改日期')),
            ],
        ),
    ]
