# Generated by Django 2.0 on 2018-05-17 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_auto_20180518_0655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cacti',
            name='link',
        ),
        migrations.AddField(
            model_name='cacti',
            name='graphid',
            field=models.CharField(default='0', max_length=10, verbose_name='图形ID'),
        ),
        migrations.AddField(
            model_name='cacti',
            name='server',
            field=models.CharField(choices=[('cacti1', 'cacti1'), ('cacti2', 'cacti2'), ('cacti3', 'cacti3')], default='cacti1', max_length=10, verbose_name='服务器'),
        ),
        migrations.AlterField(
            model_name='netflow',
            name='server',
            field=models.CharField(choices=[('netflow1', 'netflow1'), ('netflow2', 'netflow2'), ('netflow3', 'netflow3')], default='netflow1', max_length=10, verbose_name='服务器'),
        ),
    ]
